name: Multi-VM CI/CD Pipeline

on:
  push:
    branches:
      - main         # triggers Dev deployment
    tags:
      - 'staging-*'  # triggers Staging deployment
      - 'v*'         # triggers Prod deployment

jobs:
  deploy-dev:
    name: Deploy to Dev VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: Deploy to Dev
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DEV_HOST }} << 'EOF'
            cd ~/app || mkdir ~/app && cd ~/app
            git clone https://github.com/${{ github.repository }} . || git pull
            docker compose down || true
            docker compose up -d --build
          EOF

  deploy-staging:
    name: Deploy to Staging VM
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/staging-')
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      - name: Deploy to Staging
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.STAGING_HOST }} << 'EOF'
            cd ~/app || mkdir ~/app && cd ~/app
            git clone https://github.com/${{ github.repository }} . || git pull
            docker compose down || true
            docker compose up -d --build
          EOF

  deploy-prod:
    name: Deploy to Prod VM
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Deploy to Prod
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.PROD_HOST }} << 'EOF'
            cd ~/app || mkdir ~/app && cd ~/app
            git clone https://github.com/${{ github.repository }} . || git pull
            docker compose down || true
            docker compose up -d --build
          EOF
